first working version with branches
svn ls has a bug where
svn ls -r xxxxx file:///path/module would list something, but
svn ls -r xxxxx file:///path | grep module was not

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -37,11 +37,11 @@ do
     svn mkdir --parents -m "create initial directories" file:///$YAST/$MODULE/trunk file:///$YAST/$MODULE/branches file:///$YAST/$MODULE/tags \
         $(for i in `grep "Node-path: branches/" $YAST/$MODULE.dump | cut -d"/" -f 2 | sort | uniq` ; do echo -n " file:///$YAST/$MODULE/branches/$i " ; done )
     svnadmin load $YAST/$MODULE < $YAST/$MODULE.dump > $YAST/$MODULE.load 2>&1
-    svn ls file:///$YAST/$MODULE/trunk | grep -q . || echo "no trunk, aborting" && exit 1
+    svn ls file:///$YAST/$MODULE/trunk | grep -q . || { tail $YAST/$MODULE.load ; echo "no trunk, aborting" ; exit 1 ; }
   fi
 
   echo "declare MODULE=${MODULE}" > $RULEDIR/module.rule
-  svn-all-fast-export --add-metadata --identity-map $RULEDIR/yast.map --rules $RULEDIR/yast.rules $YAST/$MODULE
+  svn-all-fast-export --add-metadata --identity-map $RULEDIR/yast.map --rules $RULEDIR/yast.rules $YAST/$MODULE >stdout
   mv yast-$MODULE{,.git}
   git clone yast-$MODULE.git
 
