modules from env, better svndumpfilter3
track mkdir for all interesting paths
exclude paths that already contain module name from copy-injection

diff --git a/notes b/notes
--- a/notes
+++ b/notes
@@ -14,7 +14,7 @@ then
    svnadmin load $REPO < $DUMPFILE
 fi
 
-for MODULE in installation registration # x11 core mouse network printer ldap irda vm qt
+for MODULE in $MODULES #printer core vm qt installation #registration # x11 core mouse network printer ldap irda vm qt
 do
   export MODULE
   SKIP=false
@@ -34,15 +34,16 @@ do
   fi
   if ! $SKIP
   then
-    $svndumpfilter3 --untangle=$REPO ".*/$MODULE" "branches/.*/$MODULE" "tags/.*/$MODULE" < $DUMPFILE > $YAST/$MODULE.dump 2>dumpfilter.out
-    mkdir -p $YAST/$MODULE
+    $svndumpfilter3 --untangle=$REPO branches/SuSE-Linux-10_1-Branch ".*/$MODULE" "branches/.*/$MODULE" "tags/.*/$MODULE" < $DUMPFILE > $YAST/$MODULE.dump 2>dumpfilter.out
     svnadmin create $YAST/$MODULE
     svnadmin load $YAST/$MODULE < $YAST/$MODULE.dump > $YAST/$MODULE.load 2>&1
-    svn ls file:///$YAST/$MODULE/trunk | grep -q . || { tail $YAST/$MODULE.load ; echo "no trunk, aborting" ; exit 1 ; }
+    tail $YAST/$MODULE.load
+    svn ls file:///$YAST/$MODULE/trunk | grep -q . || { echo "no trunk, aborting" ; exit 1 ; }
   fi
 
   echo "declare MODULE=${MODULE}" > $RULEDIR/module.rule
   svn-all-fast-export --add-metadata --identity-map $RULEDIR/yast.map --rules $RULEDIR/yast.rules $YAST/$MODULE >stdout
+  rm -rf $YAST/$MODULE # cleanup to save space
   mv yast-$MODULE{,.git}
   git clone yast-$MODULE.git
 
